"""
Django settings for banana project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Корневая папка проекта
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# Секретный ключ(используется для построения шифров) Без него проект не будет работать
SECRET_KEY = 'django-insecure-&+h+l@i&&46aty+o*-&m1goa_*xewr9=7a4zjypfz-sj(c!nyy'

# режим разработки (включен или нет) При загрузки на сервер обязательно выключить, иначе небезопасно
DEBUG = True
# разрешённые хосты (с каких доменных и ip адресов есть доступ
ALLOWED_HOSTS = []


"""Установленные приложения (помимо предустановленных, обязательно 
нужно указать свои) порядок таков: приложения Django, сторонниеб из проекта"""

INSTALLED_APPS = [
    # приложения самого Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # сторонние приложения
    'rest_framework',
    # из проекта
    'account',
    'main'
]

""" промежуточные слои (специальные классы, которые отвечают за обработку
каждого запроса и ответа"""

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

"""описывается, какой файл отвечает за пути в проекте"""
ROOT_URLCONF = 'banana.urls'

# настроки шаблонов
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# веб-сервер
WSGI_APPLICATION = 'banana.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# настройки подключения к БД
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'banana',
        'USER': 'roman',
        'PASSWORD': '123',
        'HOST': 'localhost',
        'PORT': 5432
    }
}


# Валидация пароля
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Интернационализация
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# код языка
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bishkek'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# две нижние строчки нужны для правильного отображения картинок
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Настройка primary key по умолчанию (SERIAL в Django называется AutoField)
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'account.User'  # модель пользователя
